Intgrtns 237 add per domain syncs button in whmcs admin area
openprovider/Openprovider-WHMCS-domains pull request #333
Opened 2024-08-21 08:40 UTC by DaniNC

2024-09-04 09:49 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +        var_dump('DomainSyncAutoRenew');die;
remove this

2024-09-04 09:49 UTC, sampikaipakan commented on modules/registrars/openprovider/Controllers/System/DomainSyncAutoRenewController.php
> +        if(Configuration::getOrDefault('syncUseNativeWHMCS', false) == false) {
better to use ===

2024-09-04 09:52 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +        else
I can see most of the places, you added curly braces in new lines, for consitions better to use same like you did try catch

2024-09-04 09:52 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +        if($status == 'Cancelled' || $status == 'Expired' || $status == 'Transferred Away')
try to use ===

2024-09-04 09:52 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +        else
this too, curly in same line, more readble

2024-09-04 09:54 UTC, sampikaipakan requested changes

2024-09-04 09:54 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +            return true;
put a new line before return

2024-09-04 09:54 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +                        $this->op_domain             =    $this->apiHelper->getDomain($this->op_domain_obj);
why this so spaces

2024-09-04 09:54 UTC, sampikaipakan commented on modules/registrars/openprovider/src/DomainSyncAutoRenew.php
> +                if($this->objectDomain->status == 'Pending Transfer' && $op_domain_status == 'Active')
too much nested seems

2024-09-24 15:14 UTC, sapillai approved these changes
Tested the branch with latest changes, it is working as expected. Expiration date and status were synced correctly to WHMCS.

2024-09-25 12:03 UTC, chhatbarhiren approved these changes
I checked the code, didn't make sense to me but I trust Sharmi and @sapillai's review and his testing and hence, approving for good. Thank you.

2024-09-26 13:40 UTC, merged